services:
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    env_file:
      - ../../.env.common
    ports:
      - '80:80'     # HTTP
      - '81:81'     # Admin UI
      - '443:443'   # HTTPS
    environment:
      - TZ=${TZ}
    volumes:
      - ${VOLUME_ROOT}/npm/data:/data
      - ${VOLUME_ROOT}/npm/letsencrypt:/etc/letsencrypt
    networks:
      - homelab-network
