services:
  tubearchivist:
    image: bbilly1/tubearchivist:latest
    container_name: tubearchivist
    restart: always
    env_file:
      - .env
    ports:
      - 8084:8000
    environment:
      - ES_URL=http://archivist-es:9200
      - REDIS_HOST=archivist-redis
      - HOST_UID=${PUID}
      - HOST_GID=${PGID}
      - TZ=${TZ}
      - TA_HOST=${TA_HOST}
      - TA_USERNAME=${TA_USERNAME}
      - TA_PASSWORD=${TA_PASSWORD}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ${MEDIA_ROOT}/youtube:/youtube
      - ${VOLUME_ROOT}/tubearchivist/cache:/cache
    depends_on:
      - archivist-es
      - archivist-redis
    networks:
      - homelab-network

  archivist-redis:
    image: redis/redis-stack-server:latest
    container_name: archivist-redis
    restart: always
    volumes:
      - ${VOLUME_ROOT}/tubearchivist/redis:/data
    depends_on:
      - archivist-es
    networks:
      - homelab-network

  archivist-es:
    image: bbilly1/tubearchivist-es:latest
    container_name: archivist-es
    restart: always
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - discovery.type=single-node
      - path.repo=/usr/share/elasticsearch/data/snapshot
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${VOLUME_ROOT}/tubearchivist/es:/usr/share/elasticsearch/data
    networks:
      - homelab-network
