services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: always
    user: "${PUID}:${PGID}"
    ports:
      - "8090:80"
    volumes:
      - ${EXTERNAL_SSD}:/srv
      - ${VOLUME_ROOT}/filebrowser:/config
    command: ["--database", "/config/filebrowser.db"]
    networks:
      - homelab-network
